name: luna-ai-translator
region: nyc

# 静态站点配置
static_sites:
  - name: web
    github:
      repo: rozx/luna-ai-translator
      branch: main
      deploy_on_push: true
    
    # 源代码目录（项目根目录）
    source_dir: /
    
    # 构建命令（明确指定 SPA 模式）
    # 首先安装 Bun（如果未预装），然后安装依赖并使用 build:spa 脚本构建
    build_command: curl -fsSL https://bun.sh/install | bash && export PATH="$HOME/.bun/bin:$PATH" && bun install && bun run build:spa
    
    # 输出目录（Quasar SPA 构建输出到 dist/spa）
    output_dir: dist/spa
    
    # 环境变量
    envs:
      - key: NODE_ENV
        value: production
        scope: BUILD_TIME
    
    # HTTP 路由配置
    routes:
      - path: /
    
    # SPA 路由回退（Hash 路由模式下不是必需的，但保留也无妨）
    catchall_document: index.html

