name: luna-ai-translator
region: sgp

# 使用 Dockerfile 部署的配置
# 此配置使用 Dockerfile 来安装所有系统依赖，包括 Chrome 所需的库
services:
  - name: luna-app
    github:
      repo: rozx/luna-ai-translator
      branch: main
      deploy_on_push: true
    source_dir: /
    # 使用 Dockerfile 构建
    dockerfile_path: Dockerfile
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    routes:
      - path: /
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_TIME
      - key: PROXY_MODE
        value: allorigins
        scope: RUN_TIME

