/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIModelDialog: typeof import('./components/dialogs/AIModelDialog.vue')['default']
    AIModelSettingsTab: typeof import('./components/settings/AIModelSettingsTab.vue')['default']
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    AppMessage: typeof import('./components/common/AppMessage.vue')['default']
    AppSideMenu: typeof import('./components/layout/AppSideMenu.vue')['default']
    BookDialog: typeof import('./components/dialogs/BookDialog.vue')['default']
    Button: typeof import('primevue/button')['default']
    CharacterEditDialog: typeof import('./components/dialogs/CharacterEditDialog.vue')['default']
    CharacterSettingPanel: typeof import('./components/novel/CharacterSettingPanel.vue')['default']
    Chips: typeof import('primevue/chips')['default']
    Column: typeof import('primevue/column')['default']
    ConflictResolutionDialog: typeof import('./components/dialogs/ConflictResolutionDialog.vue')['default']
    CoverManagerDialog: typeof import('./components/dialogs/CoverManagerDialog.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    ExtractedTermsDialog: typeof import('./components/novel/ExtractedTermsDialog.vue')['default']
    ImportExportTab: typeof import('./components/settings/ImportExportTab.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    NovelScraperDialog: typeof import('./components/dialogs/NovelScraperDialog.vue')['default']
    ParagraphCard: typeof import('./components/novel/ParagraphCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScraperSettingsTab: typeof import('./components/settings/ScraperSettingsTab.vue')['default']
    SettingCard: typeof import('./components/novel/SettingCard.vue')['default']
    SettingsDialog: typeof import('./components/dialogs/SettingsDialog.vue')['default']
    Slider: typeof import('primevue/slider')['default']
    SyncSettingsTab: typeof import('./components/settings/SyncSettingsTab.vue')['default']
    SyncStatusPanel: typeof import('./components/sync/SyncStatusPanel.vue')['default']
    TermEditDialog: typeof import('./components/dialogs/TermEditDialog.vue')['default']
    TerminologyDialog: typeof import('./components/dialogs/TerminologyDialog.vue')['default']
    TerminologyPanel: typeof import('./components/novel/TerminologyPanel.vue')['default']
    TerminologySettingsTab: typeof import('./components/settings/TerminologySettingsTab.vue')['default']
    TestResult: typeof import('./components/ai/TestResult.vue')['default']
    ThinkingProcessPanel: typeof import('./components/ai/ThinkingProcessPanel.vue')['default']
    ToastHistoryDialog: typeof import('./components/dialogs/ToastHistoryDialog.vue')['default']
    TranslatableChips: typeof import('./components/translation/TranslatableChips.vue')['default']
    TranslatableInput: typeof import('./components/translation/TranslatableInput.vue')['default']
  }
}
