/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddChapterDialog: typeof import('./components/dialogs/AddChapterDialog.vue')['default']
    AddVolumeDialog: typeof import('./components/dialogs/AddVolumeDialog.vue')['default']
    AIModelDialog: typeof import('./components/dialogs/AIModelDialog.vue')['default']
    AIModelSettingsTab: typeof import('./components/settings/AIModelSettingsTab.vue')['default']
    ApiKeysSettingsTab: typeof import('./components/settings/ApiKeysSettingsTab.vue')['default']
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    AppMessage: typeof import('./components/common/AppMessage.vue')['default']
    AppRightPanel: typeof import('./components/layout/AppRightPanel.vue')['default']
    AppSideMenu: typeof import('./components/layout/AppSideMenu.vue')['default']
    AskUserDialog: typeof import('./components/dialogs/AskUserDialog.vue')['default']
    BatchSummaryPanel: typeof import('./components/novel/BatchSummaryPanel.vue')['default']
    BookDialog: typeof import('./components/dialogs/BookDialog.vue')['default']
    ChapterContentPanel: typeof import('./components/novel/ChapterContentPanel.vue')['default']
    ChapterSettingsPopover: typeof import('./components/novel/ChapterSettingsPopover.vue')['default']
    ChapterToolbar: typeof import('./components/novel/ChapterToolbar.vue')['default']
    CharacterEditDialog: typeof import('./components/dialogs/CharacterEditDialog.vue')['default']
    CharacterPopover: typeof import('./components/novel/CharacterPopover.vue')['default']
    CharacterSettingPanel: typeof import('./components/novel/CharacterSettingPanel.vue')['default']
    CoverManagerDialog: typeof import('./components/dialogs/CoverManagerDialog.vue')['default']
    DeleteChapterConfirmDialog: typeof import('./components/dialogs/DeleteChapterConfirmDialog.vue')['default']
    DeleteCharacterConfirmDialog: typeof import('./components/dialogs/DeleteCharacterConfirmDialog.vue')['default']
    DeleteTermConfirmDialog: typeof import('./components/dialogs/DeleteTermConfirmDialog.vue')['default']
    DeleteVolumeConfirmDialog: typeof import('./components/dialogs/DeleteVolumeConfirmDialog.vue')['default']
    EditChapterDialog: typeof import('./components/dialogs/EditChapterDialog.vue')['default']
    EditVolumeDialog: typeof import('./components/dialogs/EditVolumeDialog.vue')['default']
    ImportExportTab: typeof import('./components/settings/ImportExportTab.vue')['default']
    KeyboardShortcutsPopover: typeof import('./components/novel/KeyboardShortcutsPopover.vue')['default']
    MemoryAttachmentTag: typeof import('./components/novel/MemoryAttachmentTag.vue')['default']
    MemoryCard: typeof import('./components/novel/MemoryCard.vue')['default']
    MemoryDetailDialog: typeof import('./components/novel/MemoryDetailDialog.vue')['default']
    MemoryPanel: typeof import('./components/novel/MemoryPanel.vue')['default']
    MemoryReferencePanel: typeof import('./components/novel/MemoryReferencePanel.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    NovelScraperDialog: typeof import('./components/dialogs/NovelScraperDialog.vue')['default']
    ParagraphCard: typeof import('./components/novel/ParagraphCard.vue')['default']
    ProxySettingsTab: typeof import('./components/settings/ProxySettingsTab.vue')['default']
    RestoreDeletedItemsDialog: typeof import('./components/dialogs/RestoreDeletedItemsDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScraperSettingsTab: typeof import('./components/settings/ScraperSettingsTab.vue')['default']
    SearchToolbar: typeof import('./components/novel/SearchToolbar.vue')['default']
    SettingCard: typeof import('./components/novel/SettingCard.vue')['default']
    SettingsDialog: typeof import('./components/dialogs/SettingsDialog.vue')['default']
    SyncSettingsTab: typeof import('./components/settings/SyncSettingsTab.vue')['default']
    SyncStatusPanel: typeof import('./components/sync/SyncStatusPanel.vue')['default']
    TermEditDialog: typeof import('./components/dialogs/TermEditDialog.vue')['default']
    TerminologyPanel: typeof import('./components/novel/TerminologyPanel.vue')['default']
    TermPopover: typeof import('./components/novel/TermPopover.vue')['default']
    TestResult: typeof import('./components/ai/TestResult.vue')['default']
    ThinkingProcessPanel: typeof import('./components/ai/ThinkingProcessPanel.vue')['default']
    ToastHistoryDialog: typeof import('./components/dialogs/ToastHistoryDialog.vue')['default']
    TranslatableChips: typeof import('./components/translation/TranslatableChips.vue')['default']
    TranslatableInput: typeof import('./components/translation/TranslatableInput.vue')['default']
    TranslationHistoryDialog: typeof import('./components/dialogs/TranslationHistoryDialog.vue')['default']
    TranslationProgress: typeof import('./components/novel/TranslationProgress.vue')['default']
    VolumesList: typeof import('./components/novel/VolumesList.vue')['default']
  }
}
