/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIModelDialog: typeof import('./components/AIModelDialog.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AppMessage: typeof import('./components/AppMessage.vue')['default']
    AppSideMenu: typeof import('./components/AppSideMenu.vue')['default']
    BookDialog: typeof import('./components/BookDialog.vue')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    CoverManagerDialog: typeof import('./components/CoverManagerDialog.vue')['default']
    DataView: typeof import('primevue/dataview')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    EssentialLink: typeof import('./components/EssentialLink.vue')['default']
    ExampleComponent: typeof import('./components/ExampleComponent.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    NovelScraperDialog: typeof import('./components/NovelScraperDialog.vue')['default']
    Paginator: typeof import('primevue/paginator')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDialog: typeof import('./components/SettingsDialog.vue')['default']
    Sidebar: typeof import('primevue/sidebar')['default']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    SyosetuScraperDialog: typeof import('./components/SyosetuScraperDialog.vue')['default']
    TestResult: typeof import('./components/TestResult.vue')['default']
    ToastHistoryDialog: typeof import('./components/ToastHistoryDialog.vue')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
  }
}
